name: State machine compatability labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - 'main'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ADD_TO_PROJECT_PAT }}
        with: #Require one of the following labels
          mode: exactly
          count: 1
          labels: "V:State_Machine/breaking, V:State_Machine/compatible/no_backport, V:State_Machine/compatible/backport"